# Generated by Django 3.2.4 on 2021-06-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тег')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Задача')),
                ('text', models.TextField()),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('finish_date', models.DateTimeField(verbose_name='Дата выполнения')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('tag', models.ManyToManyField(blank=True, related_name='tasks', to='api.Tag')),
            ],
        ),
    ]
